<?php
	define('_danhmuc','Category');
	define('_aboutus','About Us');
	define('_lienhe','Contact');
	define('_news','News');
	define('_typekey','Press keywords ...');
	define('_viewmore','Read more');
	define('_viewall','View all');
	define('_lastpost','Last post news');
	define('_linkwebsite','Connect website');
	define('_Category_pro','Products Category');
	define('_conect_us','Connect with us');
	define('_enter_content_search','Enter search text');
	define('_support_online','Support Online');
	define('_register_email','Register email');
	define('_type_email','Please enter email!');
	define('_product_discovery','Product Discovery');
	define('_send','Send');
	define('_trangchu','Home');
	define('_ngaydang','Day post');
	define('_baivietlienquan','Relative post');
	define('_updating','Updating...');
	define('_noidunglienhe','Contact Information');
	define('_hoten','Full name');
	define('_typehoten','Please enter full name');
	define('_sodienthoai','Phone number');
	define('_typesodienthoai','Please enter phone number');
	define('_address','Address');
	define('_typeaddress','Please enter address');
	define('_content','Contents');
	define('_typecontent','Please enter contents');
	define('_captcha','Security Code');
	define('_typecaptcha','Please enter the security code');
	define('_price','Price');
	define('_buypro','Buy');
	define('_codepro','Product code');
	define('_detailpro','View detail');
	define('_pro_relative','Related Products');
	define('_pro_detail','Products Details');
	define('_cart','Cart');
	define('_namepro','Name Product');
	define('_price_sale','Price Promotion');
	define('_number','Number');
	define('_money','Amount');
	define('_del','Delete');
	define('_redel','Delate comfirm');
	define('_totalmoney','Total');
	define('_infouser','Information Order');
	define('_timeanddetail','Add notes');
	define('_timedelivery','Delivery time');
	define('_daydelivery','Delivery date');
	define('_message','Message');
	define('_formpayment','Pay');
	define('_sendcart','Send orders and payment »');
	define('_buycart','« Continue Shopping');
	define('_cartblank','Currently no products in your shopping cart. Click here to return to the previous page.');
	define('_search','Search');
	define('_ketquatimkiem','Search Results');
	define('_question','Hỏi');
	define('_repply','Đáp');
	define('_title_ques','Bạn có thắc mắc? Vui lòng điền vào form bên dưới!');
	define('_questionct','Đặt câu hỏi');
	
	define('_thongketruycap','Statistical Access');
	define('_dangtruycap','Online');
	define('_trongngay','Today');
	define('_trongtuan','Week');
	define('_trongthang','Month');
	define('_tongtruycap','Total Access');
	
	define('_comment','Comments');
	define('_share','Share');
	
	define('_dangky','Register');
	define('_dangnhap','Login');
	define('_dichvuhangdau','Dịch vụ hàng đầu');
	define('_hotrotructuyen','Support Online');
	define('_tintuctrongngay','Tin tức trong ngày');
	define('_xemthem','Read more');
	define('_contac_us','Contact us');
	define('_email','email');
	define('_bandochiduong','Bản đồ chỉ đường');
	define('_dangxuat','Logout');
	define('_guithongtin','Gửi thông tin');
	
	define('_thanhcong','Success');
	define('_dangnhapthanhcong','Login Success');
	define('_vuilongchogiaylat','Vui lòng chờ giây lát');
	define('_dangnhapthatbai','Đăng nhập thất bại');
	define('_saitaikhoanhoacmatkhau','Sai tài khoản hoặc mật khẩu');
	define('_dangkythanhcongvuilongchoadminduyettrongvong24h','Đăng ký thành công! Vui lòng chờ admin duyệt trong vòng 24h');
	define('_taikhoan','User name');
	define('_nhaptaikhoan','Enter account name');
	define('_tentaikhoandatontai','This account has already existed');
	define('_luuy','Notes');
	define('_tentaikhoanphaikhongcodauvakhoangtrong','Account Name must not have stamps and blanks');
	define('_matkhau','Password');
	define('_nhapmatkhau','Enter the password');
	define('_nhaplaimatkhau','Enter the password');
	define('_matkhaukhongtrungkhop','Passwords do not match');
	define('_nhaphoten','Full name');
	define('_nhapemail','Enter email');
	define('_emaildatontai','Email is exist');
	define('_dienthoai','Phone');
	define('_nhapdienthoai','Enter the Phone');
	define('_diachi','Address');
	define('_nhapdiachi','Enter the Address');
	define('_ngaysinh','Birth day');
	define('_ngay','Day');
	define('_thang','Month');
	define('_nam','Year');
	define('_gioitinh','Sex');
	define('_boy','Male');
	define('_nu','FeMale');
	define('_dangky','Register');
	
	
	define('_design','Design by');
	define('_sp_hot','Featured Products');
	define('_pro_detail','Product Details');
	define('_xemchitiet','View Details');
	define('_spmoi','New Products');
	define('_doitac','Partners');
	define('_sp_chon','Selected products');

	define('_tongdai','Phone support');
	define('_dangkynhanbantin','Receive newsletter');
	define('_nhapdiachiemail','Enter your email address to receive alerts from websites:');
	define('_huydangky','Cancel registration');
	define('_sanphamnoibat','Hot Products');
	define('_masp','Code');
	define('_sanpham','Products');
	define('_dichvu','Services');
	define('_tinhtranghang','Status');
	define('_conhang','Stocking');
	define('_hethang','Out of stock');

	define('_nhacungcap','Supplier');
	define('_nhasanxuat','Producer');
	define('_tinmoinhat','Latest news');
	define('_danhmucsanpham','Products catagory');
	define('_danhmucdichvu','Services catagory');

	define('_sptieubieu','Featured products');
	define('_spmoi','New products');
	define('_spbanchay','Selling products');

	define('_banggia','price list');
	define('_taisao','Why choose us');
	define('_duannoibat','Featured project');	
	define('_vechungtoi','About Us');
	define('_xemtatca','View All');
	define('_tuvan','Advisory');
	define('_guicauhoi','Submit a question to us');
	define('_cauhoi','Question');
	define('_chinhsachquydinh','Policies & Regulations');

	define('_nhapemailcuaban','Enter your email');
	define('_mausac','Color');
	define('_giabansi','Wholesale price contact');
	define('_dt_qc','Partners');
	define('_tintucnoibat','Featured news');
	define('_nhantinchochungtoi','Send a message');
?>